# Copyright 2025 Project-Numina and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COMMON_STOPWORDS: set[str] = {
    # Basic English function words:
    "a",
    "an",
    "the",
    "and",
    "or",
    "of",
    "to",
    "in",
    "on",
    "for",
    "with",
    "by",
    "from",
    "as",
    "at",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "it",
    "its",
    "this",
    "that",
    "these",
    "those",
    "we",
    "you",
    "they",
    "he",
    "she",
    "i",
    "there",
    "their",
    "your",
    "his",
    "her",
    "not",
    "no",
    "yes",
    "but",
    "if",
    "only",
    "than",
    "then",
    "so",
    # Proof “glue” words / standard moves:
    "let",
    "assume",
    "suppose",
    "consider",
    "take",
    "fix",
    "define",
    "set",
    "choose",
    "given",
    "given any",
    "given arbitrary",
    "each",
    "every",
    "all",
    "any",
    "either",
    "otherwise",
    "exists",
    "exist",
    "such",
    "wlog",
    "without loss",
    "we have",
    "we obtain",
    "we get",
    "we see",
    "we conclude",
    "have",
    "obtain",
    "get",
    "see",
    "conclude",
    "note",
    "notice",
    "observe",
    "clearly",
    "obviously",
    "evidently",
    "hence",
    "thus",
    "therefore",
    "so that",
    "then we have",
    "implies",
    "imply",
    "⇒",
    "→",
    "⇔",
    "iff",
    "since",
    "because",
    "given that",
    # Structural tags / references:
    "theorem",
    "lemma",
    "corollary",
    "proposition",
    "claim",
    "definition",
    "remark",
    "example",
    "proof",
    "qed",
    "∎",
    "□",
    "■",
    # Common mathematical connectives / short latex commands:
    "∀",
    "∃",
    "\\forall",
    "\\exists",
    "\\rightarrow",
    "\\implies",
    "\\Rightarrow",
    "\\iff",
    "\\Leftrightarrow",
    "\\to",
    "∴",
    "∵",
    # Short inline fillers that add little semantic weight:
    "now",
    "next",
    "finally",
    "lastly",
    "again",
    "furthermore",
    "moreover",
    "first",
    "second",
    "third",
    # Very short number-words (optional; remove if you need them):
    "one",
    "two",
    "three",
}
